//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTickets
    {
        public long AssetId { get; set; }
        public long TicketId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
