//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictItems
    {
        public long Id { get; set; }
        public long TypeId { get; set; }
        public string Label { get; set; }
        public string Value { get; set; }
        public int Sort { get; set; }
        public byte Status { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual DictTypes DictTypes { get; set; }
    }
}
