//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowDesk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowDeskEntities : DbContext
    {
        public FlowDeskEntities()
            : base("name=FlowDeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<RoleMenus> RoleMenus { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<TicketAttachments> TicketAttachments { get; set; }
        public virtual DbSet<TicketCategories> TicketCategories { get; set; }
        public virtual DbSet<TicketComments> TicketComments { get; set; }
        public virtual DbSet<TicketFlowLogs> TicketFlowLogs { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<AssetOpLogs> AssetOpLogs { get; set; }
        public virtual DbSet<Assets> Assets { get; set; }
        public virtual DbSet<AssetTypes> AssetTypes { get; set; }
        public virtual DbSet<AssetTickets> AssetTickets { get; set; }
        public virtual DbSet<AuditLogs> AuditLogs { get; set; }
        public virtual DbSet<DictItems> DictItems { get; set; }
        public virtual DbSet<DictTypes> DictTypes { get; set; }
    }
}
