//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketFlowLogs
    {
        public long Id { get; set; }
        public long TicketId { get; set; }
        public Nullable<byte> FromStatus { get; set; }
        public byte ToStatus { get; set; }
        public string Action { get; set; }
        public long OperatorId { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
