//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAttachments
    {
        public long Id { get; set; }
        public long TicketId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string ContentType { get; set; }
        public long UploadedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
